name: golang-pipeline
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4

      - name: Test
        run: go test -v ./...
  lint:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - uses: golangci/golangci-lint-action@v9
        with:
          version: v2.14.0
          install-mode: binary